export const REQUEST_FULFILLED = "REQUEST_FULFILLED";
export const REQUEST_PENDING = "REQUEST_PENDING";
export const REQUEST_REJECTED = "REQUEST_REJECTED";

export const STORE_CUSTOMER_INFO = "STORE_CUSTOMER_INFO";
export const CLEAR_CUSTOMER_INFO = "CLEAR_CUSTOMER_INFO";

export const STORE_USER_INFO = "STORE_USER_INFO";
export const CLEAR_USER_INFO = "CLEAR_USER_INFO";

export const STORE_APPLICATION_ID = "STORE_APPLICATION_ID";
export const CLEAR_APPLICATION_ID = "CLEAR_APPLICATION_ID";

export const STORE_PICTURE_INFO = "STORE_PICTURE_INFO";
export const STORE_PICTURES = "STORE_PICTURES";
export const DELETE_PICTURE_INFO = "DELETE_PICTURE_INFO";
export const CLEAR_PICTURES = "CLEAR_PICTURES";
export const REMOVE_PICTURE_BY_ID = "REMOVE_PICTURE_BY_ID";

export const STORE_RESULTS = "STORE_RESULTS";
export const CLEAR_RESULTS = "CLEAR_RESULTS";
export const STORE_INCIDENT_STATE = "STORE_INCIDENT_STATE";
export const STORE_APPRAISAL = "STORE_APPRAISAL";
export const CLEAR_APPRAISAL = "CLEAR_APPRAISAL";
export const CLONE_APPRAISAL = "CLONE_APPRAISAL";
export const CLEAR_CLONED_APPRAISAL = "CLEAR_CLONED_APPRAISAL";
export const UPDATE_APPRAISAL = "UPDATE_APPRAISAL";
export const UPDATE_DAMAGE_SIZE = "UPDATE_DAMAGE_SIZE";
export const ADD_APPRAISAL_PART = "ADD_APPRAISAL_PART";
export const ADD_APPRAISAL_DAMAGE = "ADD_APPRAISAL_DAMAGE";
export const REMOVE_APPRAISAL_DAMAGE = "REMOVE_APPRAISAL_DAMAGE";

export const UPDATE_SHAPE = "UPDATE_SHAPE";
export const ADD_PART = "ADD_PART";
export const UPDATE_PART = "UPDATE_PART";
export const STORE_PARTS = "STORE_PARTS";
export const CLEAR_PARTS = "CLEAR_PARTS";
export const REMOVE_PART = "REMOVE_PART";
export const REMOVE_PARTS_BY_IMAGE_ID = "REMOVE_PARTS_BY_IMAGE_ID";
export const ADD_DAMAGE = "ADD_DAMAGE";
export const UPDATE_DAMAGE = "UPDATE_DAMAGE";
export const STORE_DAMAGES = "STORE_DAMAGES";
export const CLEAR_DAMAGES = "CLEAR_DAMAGES";
export const REMOVE_DAMAGE = "REMOVE_DAMAGE";
export const SHOW_DELETE_ALERT = "SHOW_DELETE_ALERT";
export const REMOVE_DAMAGES_BY_IMAGE_ID = "REMOVE_DAMAGES_BY_IMAGE_ID";
export const RESET_MODIFIED_FLAG = "RESET_MODIFIED_FLAG";

export const STORE_INCIDENTS = "STORE_INCIDENTS";
export const CLEAR_INCIDENTS = "CLEAR_INCIDENTS";
export const DIRTY_CURRENT_INCIDENT = "DIRTY_CURRENT_INCIDENT";
export const STORE_CURRENT_INCIDENT = "STORE_CURRENT_INCIDENT";
export const CLEAR_CURRENT_INCIDENT = "CLEAR_CURRENT_INCIDENT";
export const DELETE_IMAGES = "DELETE_IMAGES";

export const STORE_IMAGES = "STORE_IMAGES";
export const REMOVE_IMAGE = "REMOVE_IMAGE";

export const STORE_GRADES = "STORE_GRADES";
export const CLEAR_GRADES = "CLEAR_GRADES";

export const VIN_NUMBER = "VIN_NUMBER";
export const DELETE_VIN_NUMBER = "DELETE_VIN_NUMBER";
export const VIN_READING = "VIN_READING";
export const VIN_SUCCESS = "VIN_SUCCESS";
export const VIN_FAILURE = "VIN_FAILURE";

export const CHOOSE_ANGLE_INFO = "CHOOSE_ANGLE_INFO";
export const CLEAR_CHOOSE_ANGLE_INFO = "CLEAR_CHOOSE_ANGLE_INFO";

export const REPORT_ID = "REPORT_ID";
export const CLEAR_REPORT_ID = "CLEAR_REPORT_ID";

export const POSE_IMAGES = "POSE_IMAGES";
export const DELETE_POSE_IMAGES = "DELETE_POSE_IMAGES";
export const CLEAR_POSE_IMAGES = "CLEAR_POSE_IMAGES";
export const SELECT_MORE_POSES = "SELECT_MORE_POSES";
export const DELETE_SELECT_MORE_POSES = "DELETE_SELECT_MORE_POSES";
export const CLEAR_SELECT_MORE_POSES = "CLEAR_POSE_IMAGES";

export const SELECTED_POSES = "SELECTED_POSES";
export const UPLOADED_POSES = "UPLOADED_POSES";

export const CLEAR_INCIDENT_ID =  "CLEAR_INCIDENT_ID";

export const ADD_TOTAL_IMAGES = "ADD_TOTAL_IMAGES";

export const STORE_ESTIMATE = "STORE_ESTIMATE";

export const ISUNDERWRITING = "ISUNDERWRITING";
export const INTACT_DAMAGED = "INTACT_DAMAGED";
export const ISFOURPASE = "ISFOURPASE";

export const STORE_ANALYSIS_RESULTS = 'STORE_ANALYSIS_RESULTS';

export const RE_EDIT = 'RE_EDIT';
export const RE_EDIT_POSE_NAME = 'RE_EDIT_POSE_NAME';
export const RE_EDIT_POSE_PICTURE = 'RE_EDIT_POSE_PICTURE';
export const REMOVE_TOTAL_IMAGES ='REMOVE_TOTAL_IMAGES';
export const RE_UPLOAD_FROM_POSES = 'RE_UPLOAD_FROM_POSES';
export const RE_UPLOAD = 'RE_UPLOAD';
export const STORE_INFERRED_POSE = 'STORE_INFERRED_POSE';