export default [
  { key: "fairing", name: "fairing" },
  { key: "front_panel", name: "front panel" },
  { key: "front_panel_left", name: "front panel left" },
  { key: "front_panel_right", name: "front panel right" },
  { key: "headlight", name: "headlight" },
  { key: "turn_signal_front_right", name: "turn signal front right" },
  { key: "turn_signal_front_left", name: "turn signal front left" },
  { key: "mirror_left", name: "mirror left" },
  { key: "mirror_right", name: "mirror right" },
  { key: "instrument", name: "instrument" },
  { key: "seat", name: "seat" },
  { key: "seat_bottom", name: "seat_bottom" },
  { key: "seat_rack", name: "seat_rack" },
  { key: "front_wheel_rack", name: "front_rack" },
  { key: "handlebar_rack", name: "handlebar_rack" },
  { key: "wheel_front", name: "wheel front" },
  { key: "fender_front", name: "front fender" },
  { key: "brake_front", name: "front brake" },
  { key: "wheel_rear", name: "wheel rear" },
  { key: "fender_rear", name: "rear fender" },
  { key: "brake_rear", name: "rear brake" },
  { key: "brake_light_rear", name: "rear brake light" },
  { key: "turn_signal_rear_right", name: "turn signal rear right" },
  { key: "turn_signal_rear_left", name: "turn signal rear left" },
  { key: "back_panel_lower", name: "back panel lower" },
  { key: "back_panel_upper", name: "back panel upper" },
  { key: "mud_guard", name: "mud guard" },
  { key: "rocker_panel_left", name: "rocker panel left" },
  { key: "rocker_panel_right", name: "rocker panel right" },
  { key: "side_panel_left", name: "side panel left" },
  { key: "side_panel_right", name: "side panel right" },
  { key: "engine", name: "engine" },
  { key: "exhaust_muffler", name: "exhaust muffler" },
  { key: "inside_front_panel", name: "inside front panel" },
  { key: "floor_panel", name: "floor panel" },
  { key: "handlebar_right", name: "handlebar right" },
  { key: "handlebar_left", name: "handlebar left" },
  { key: "license_plate", name: "license plate" }
];
