export default [
  { key: "fender", name: "fender", code: 202 },
  { key: "quarter_panel", name: "quarter panel", code: 203 },
  { key: "front_door_panel", name: "front door panel", code: 204 },
  { key: "rear_door_panel", name: "rear door panel", code: 205 },
  { key: "hood", name: "hood", code: 206 },
  { key: "trunk", name: "trunk", code: 207 },
  { key: "roof", name: "roof", code: 208 },
  { key: "front_bumper", name: "front bumper", code: 210 },
  { key: "rear_bumper", name: "rear bumper", code: 211 },
  { key: "side_mirror", name: "side mirror", code: 222 },
  { key: "door_handle", name: "door handle", code: 223 },
  { key: "grille", name: "grille", code: 224 },
  { key: "emblem", name: "emblem", code: 236 },
  { key: "lower_bumper_grille", name: "lower bumper grille", code: 237 },
  { key: "rocker_panel", name: "rocker panel", code: 238 },
  { key: "rear_tail_skirt", name: "rear tail skirt", code: 239 },
  { key: "head_light", name: "head light", code: 241 },
  { key: "tail_light", name: "tail light", code: 242 },
  { key: "fog_light", name: "fog light", code: 246 },
  { key: "wheel", name: "wheel rim", code: 250 },
  { key: "glass", name: "glass", code: 260 },
  { key: "windshield", name: "windshield", code: 261 },
  { key: "rear_back_glass", name: "rear back glass", code: 262 },
  { key: "front_door_glass", name: "front window glass", code: 263 },
  { key: "rear_door_glass", name: "rear window glass", code: 264 },
  { key: "quarter_glass", name: "quarter glass", code: 265 },
  { key: "license_plate", name: "license plate", code: 272 },
  { key: "front_bumper_cover", name: "front bumper cover", code: 2001 },
  { key: "rear_bumper_cover", name: "rear bumper cover", code: 2002 },
  { key: "bumper_spoiler", name: "bumper spoiler", code: 2003 },
  { key: "bumper_valance_panel", name: "bumper valance panel", code: 2004 },
  { key: "lower_bumper_valance_panel", name: "lower bumper valance panel", code: 2005 },
  { key: "rear_bumper_step_pad", name: "rear bumper step pad", code: 2006 },
  { key: "bumper_impact_bar", name: "bumper impact bar", code: 2007 },
  { key: "fender_Wheel_liner", name: "fender wheel liner", code: 2008 },
  { key: "liftgate_shell", name: "liftgate shell", code: 2009 },
  { key: "liftgate_glass", name: "liftgate glass", code: 2010 },
  { key: "pickup_bed_side_panel", name: "pickup bed side panel", code: 2011 },
  { key: "quarter_outer_panel", name: "quarter outer panel", code: 2012 },
  { key: "quarter_inner_Panel", name: "quarter inner Panel", code: 2013 },
  { key: "tailgate_shell", name: "tailgate shell", code: 2014 },
  { key: "mud_flap", name: "mud flap", code: 2015 },
  { key: "turn_signal_light", name: "turn signal light", code: 2017 },
  { key: "sunroof_frame", name: "sunroof frame", code: 2018 },
  { key: "fender_vent", name: "fender vent", code: 2019 },
  { key: "wheel_arch_panel", name: "wheel arch panel", code: 2020 },
  { key: "pillar", name: "pillar", code: 2021 },
  { key: "license_plate_bracket", name: "license plate bracket", code: 2022 },
  { key: "door_shell", name: "door shell", code: 2023 },
  { key: "door_moulding", name: "door moulding", code: 2024 },
];

// boot_trunk ?
//{ key: "luggage_lid", name: "luggage lid", code: 207 },
// license plate has 236 in algo
//{ key: "emblem", name: "emblem", code: 236 },
// there is no part with the code 247 in the algo
//{ key: "license_plate", name: "license plate", code: 247 }
// straight up dont have this in the applications
//{ key: "glass", name: "glass", code: 260 }
